cart/urls.py


from django.urls import path
from .views import add_product,remove_product,decrement_product,clear_cart,add_product_two,show_product_
app_name = "cart" 
urlpatterns = [
    path('add_product/<int:product_id>/',add_product,name='add_product'),
    path('remove_product/<int:product_id>/',remove_product,name='remove_product'),
    path('decrement_product/<int:product_id>/',decrement_product,name='decrement_product'),
    path('clear/',clear_cart,name='clear_cart'),
    path('add_product_two/<int:product_id>/',add_product_two,name='add_product_two'),
    path('product/<int:product_id>',show_product_,name='product'),
]

webs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('miwebapp.urls')),
    path('',include('rutinasapp.urls')),
    path('',include('forms.urls')),
    path('',include('auntenti.urls')),
    path('',include('products.urls')),
    path('',include('cart.urls')),
    path('',include('orders.urls')),
]
#urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import redirect, render
from products.models import Product
from django.contrib.auth.decorators import login_required
from .cart import Cart
from django.contrib import messages

@login_required(login_url='acceso')
def add_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.add(product=product)
    messages.success(request,'Producto agregado')
    return redirect('listproducts')

@login_required(login_url='acceso')
def add_product_two(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.add(product=product)
    return redirect('carrito')


@login_required(login_url='acceso')
def remove_product(request, product_id):
    cart = Cart(request)
    producto = Product.objects.get(id=product_id)
    cart.remove(producto)
    return redirect('carrito')


@login_required(login_url='acceso')
def decrement_product(request, product_id):
    cart = Cart(request)
    producto = Product.objects.get(id=product_id)
    cart.decrement(product=producto)
    return redirect('carrito')


@login_required(login_url='acceso')
def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect('carrito')


def show_cart(request):
    return render(request, 'cart/widget.html')

def show_product_(request,product_id):
    producto=Product.objects.get(pk=product_id)
    return render(request,'products/one_product.html',{
    'nombre':producto.name,'categoria':producto.name,
    'imagen':producto.image.url,'info':producto.detail,'precio':
    producto.price,'disponibilidad':producto.available
    })

cart/templates/cart/widget.html
{% extends 'miwebapp/index.html' %}
{% load static %}
{% load cart.cart_tags %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
{% block content %}

<title>Carrito de compras</title>
<link rel="icon" href="../../static/miwebapp/img/muscle.png">
<div class="table-responsive">
<table class="table" style="background-color: white;font-size: larger;">
    <head>
         <tr>
            <th colspan="3" class="text-center">
                Carrito
            </th>            
        </tr>
        <tr>
            <th class='text-center' >Producto</th>
            <th  class='text-center'>Cantidad</th>
            <th  class='text-center'>Acciones</th>
    </head> 
    <tbody>
        {% if request.session.cart.items %}
            {% for i,j in request.session.cart.items %}
                <tr class="text-center">
                    <td> <a class="bey" href="{% url 'product' i %}">{{j.name}}</a>
                        {% if j.image %}
                        <div class="row">
                            <div class="text-center">
                               <a  href="{% url 'product' i %}"><img class="img-thumbnail" src="{{j.image}}" style="width:60px;height:60px;" alt="topo"></a>
                            </div>
                            
                        </div>
                        
                        {% endif %}
                    </td>                    
                    <td>{{j.quantity}}</td>

                   
                    <td>
                  <a
                            href="{% url 'cart:add_product_two' j.product_id %}"
                            class="btn btn-sm btn-success"
                        >
                             +

                        </a>
                        <a
                           href="{% url 'cart:decrement_product' j.product_id %}" 
                           class="ml-2 btn-sm btn btn-danger"

                        >
                             -
                        </a>
                        Total {{j.price|multiply:j.quantity|money_format:'$'}}
                        <a class="btn btn-warning btn-sm" href="{% url 'cart:remove_product' j.product_id %}">Eliminar</a>

                </tr>


            {% endfor %} 
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                          No tienes productos en el carrito
                    </div>

        {% endif %}
    </tbody>  
    <tfoot>
        <tr>
            <td>
                Total: {{ cart_total_amount|money_format:'$' }}
            </td>
        </tr>
        {% if request.session.cart.items %}
            <tr>
                 <td>
                    <a class="btn btn-success" href="{% url 'process_order' %}">Crear pedido</a>
                 </td>
            </tr>
        {% endif %}
    </tfoot>
</table>
<div class="text-center"  id="final" >
    <a class='btn btn-info' href="{% url 'listproducts' %}">¡Ver más productos! </a> 
</div>
</div>
{% endblock %}