cart/urls.py


from django.urls import path
from .views import add_product,remove_product,decrement_product,clear_cart,add_product_two,show_product_
app_name = "cart" 
urlpatterns = [
    path('add_product/<int:product_id>/',add_product,name='add_product'),
    path('remove_product/<int:product_id>/',remove_product,name='remove_product'),
    path('decrement_product/<int:product_id>/',decrement_product,name='decrement_product'),
    path('clear/',clear_cart,name='clear_cart'),
    path('add_product_two/<int:product_id>/',add_product_two,name='add_product_two'),
    path('product/<int:product_id>',show_product_,name='product'),
]

products/urls.py

from django.urls import path
from .views import indexs,show_product_
from products import views
urlpatterns=[
    path('listproducts/',indexs,name='listproducts'),
    path('product/<int:product_id>',show_product_,name='product'),
   
]

webs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('miwebapp.urls')),
    path('',include('rutinasapp.urls')),
    path('',include('forms.urls')),
    path('',include('auntenti.urls')),
    path('',include('products.urls')),
    path('',include('cart.urls')),
    path('',include('orders.urls')),
]
#urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/models.py

from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=300)
    featured=models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table='categories_shop'
        verbose_name='Categoria'
        verbose_name_plural='Categorias'
        ordering=['id']
class Product(models.Model):
    name=models.CharField(max_length=300)
    slug=models.SlugField()
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='productos',blank=False)
    excerpt = models.TextField(max_length=200, verbose_name='Extracto')
    detail=models.TextField(max_length=1000,verbose_name='Informacion del producto')
    price=models.FloatField()
    available=models.BooleanField(default=True,verbose_name='Disponibilidad')

    def __str__(self):
        return self.name
    
    class Meta:
        db_table='products'
        verbose_name='Producto'
        verbose_name_plural='Productos'
        ordering=['id']

products/views.py

from django.shortcuts import render
from cart.cart import Cart
# Create your views here.
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Product
from django.core.paginator import Paginator
def indexs(request):
    cart=Cart(request)
    listado_products=Product.objects.all()
    paginator=Paginator(listado_products,3)
    pagina=request.GET.get('page') or 1
    productos=paginator.get_page(pagina)
    pagina_actual=int(pagina)
    paginas=range(1,productos.paginator.num_pages+1)
    return render(request,'products/listado.html',{'productos':productos,'paginas':paginas,'pagina_actual':pagina_actual})

@login_required(login_url='acceso')
def listado_productos(request):
    cart = Cart(request)
    products=Product.objects.all()
    return render(request,'products/listado.html',{
        'products':products
    })

def show_product_(request,product_id):
    producto=Product.objects.get(pk=product_id)
    return render(request,'products/one_product.html',{
    'nombre':producto.name,'categoria':producto.category,
    'extracto':producto.excerpt,
    'imagen':producto.image.url,'info':producto.detail,'precio':
    producto.price,'disponibilidad':producto.available,'id':producto.id
    })

products/templates/products/listado.html
{% extends 'miwebapp/index.html' %}

{% load static %}


{% load cart.cart_tags %}

{% block title %}Tienda{% endblock %}

{% block content %}

    Total {{ cart_total_amount|money_format:'$'}}
 
<div class="row">
    <div class="col-15">
        <div class="row"  >
            {% for i in productos %}
              <div class="col-md-3 col-sm-12 col-lg-4" style="">
                  <div class="card" style="width: 100%;">
                    {% if i.image %}
                    <div style='overflow: hidden;'>
                        <img src="{{i.image.url}}" style="width: 100%;transition: all 0.3s;" class='card-img-top' alt="{{i.name}}">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">{{i.name}}</h5>
                        <p class='card-text text-center'>{{i.excerpt}}</p>
                        <p class="card-text text-center">Categoria: {{i.category}}</p>
                        <p class='card-text text-center'>Disponibilidad:</p>
                        {% if i.available == 1 %}
                        <div class='text-center text-success'>Disponible</div>
                        <div class='card-footer text-center'>
                            <a class='btn btn-success' href="{% url 'product' i.id %}">Ver producto</a>
                        </div>
                        {% else %}
                        <div class='text-danger text-center'>Agotado</div>
                        {% endif %}
                    </div>
                   
                    {% endif %}
                  </div>
                  <br>

              </div>
                    
            {% endfor %}

        </div>
    </div>
    <div class='col-3'>
    </div>
    <br>
</div>
{% include "products/paginacion.html" %}
{% endblock %}

products/templates/products/one_product.html
{% extends 'miwebapp/index.html' %}
{% load static %}
{% block content %}

<div class="container" id="one" >
    <div class="card" style="margin: auto;">
        <img class="" src="{{imagen}}">
        <div class="card-body" style="text-align:center;">
            <h1>{{nombre}}</h1>
            <h5 style="font-weight: 500;">${{precio}}</h5>
            <p style='font-weight:bold;'>Descripción:</p>
            <p style="overflow: auto;max-height: 150px;font-style:oblique;text-align: justify;">{{info}}</p>

            <a class='btn btn-success' href="{% url 'cart:add_product' id %}">Agregar al carrito</a>
        </div>
    </div>
    <br> 
</div>


{% endblock %}

products/templates/products/paginacion.html
<div class="row mt-3 justify-content-center">
    <nav>
        <ul class="pagination" style="overflow: auto;">
            {% if productos.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">Primera</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{posts.previous_page_number}}">&laquo;</a>
            </li>
            {% endif %}

            {% for i in paginas %}
                 <li class='page-item' {% if pagina_actual == i %} active {% endif %}>
                    <a class="page-link" href="?page={{i}}">{{i}}</a>
                </li>
           
            {% endfor %}
        
       
            {% if productos.has_next %}
            <li  class="page-item">
                <a class='page-link' href="?page={{productos.next_page_number}}">&raquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{productos.paginator.num_pages}}">última página</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    
</div>